### PR TITLE
Update altspace.json

### PR DESCRIPTION
**Pull request by GrumpyCrouton**

### CODE REVIEW

**Comment by stevenvergenz** [comment]
Oh boy lol, it's happening! Just do a validation pass with that testing page I showed you before, and fix the "whose" vs "who's".

We might want to consider playing some test rounds with these cards, as I'm not sure how well most of the white cards would work with them.

**Comment by GrumpyCrouton** [comment]
"http://www.elearnenglishlanguage.com/blog/english-mistakes/whos-vs-whose/"

I am not able to do validation passes currently, I'm at work. But when I get home, I will set up a server and of course do that.

**Comment by stevenvergenz** [comment]
It should be "Who's your _______?", right? Also, "Your mother." is in there twice.

**Comment by GrumpyCrouton** [comment]
Yes, you're right, my bad.

And yeah I'm not sure how I did that, I probably duplicated the line because I thought of another one and forgot halfway through or something. They should both be fixed now.

**Comment by stevenvergenz** [comment]
I don't think JSON supports comments like JS does, so those'll need to be stripped out. Other than that, it's just waiting for a spacing test and it's good to go!

**Comment by GrumpyCrouton** [comment]
Comments have been stripped. Don't worry, you won't have to babysit me like this forever, I'll get it eventually :P

I don't get off work for another 8 hours or so (ugh 12 hour days), so I may add more if I think of more in that time. I will be sure to check spacing when I get home.

**Comment by stevenvergenz** [comment]
I'll leave this PR open for a couple days then, let me know when you're satisfied.

**Comment by GrumpyCrouton** [comment]
I mean as soon as I'm able to check it, you can pull it. If I think of more afterwards I'll just do another PR.

**Comment by GrumpyCrouton** [comment]
It looks like I will be heading home in an hour and a half. Do you think you could write up a quick little server config thing? I'm not exactly sure how to set it up based on looking at the index page.

**Comment by GrumpyCrouton** [comment]
That should be the last commit for this list mate, they all fit on the cards properly. I hope to see this in the game tonight! :D

**Comment by stevenvergenz** [comment]
This is an intense list! A couple comments:
- The text is automatically scaled down if the string is too long to fit on the card. Several of your submissions are doing that, keep an eye out for it.
- Is "Heroine addiction" a pun, or did you mean "Heroin"?
- Are you making these up, or are they coming from somewhere?

**Comment by GrumpyCrouton** [comment]
- I noticed that, I tried to cut them down. Several of them were scaled way lower than they are now.
- I actually meant to put both in there.
- They are just coming to my mind mostly, but some of them I had seen some social media posts or something and found the sentence or phrase funny (Basically madlibing) and threw in a blank space or changed the wording to fit the cards. None of them are from other games or anything.

**Comment by GrumpyCrouton** [comment]
All right, the rest of the formatting should be good Steven, again hope to see these in-game tonight :3

**Comment by falkrons** [comment]
Hey Grumpy. These probably won't be implemented tonight as the team is currently discussing how we want to go about this process. Please be patient with us as we all work other jobs and do this in hobby/spare time.

**Comment by GrumpyCrouton** [comment]
No problem falkrons.

**Comment by GrumpyCrouton** [comment]
Any updates on this? I am unfortunately finding it harder and harder to find games with more than just a couple people. I think people are losing interest but I'm hoping people are just busy 3:

**Comment by stevenvergenz** [comment]
Hey Grumpy, sorry for the delay. We're gonna try to handle these by tomorrow, we've been trying to find a time to test them out, play a couple rounds.

**Comment by GrumpyCrouton** [comment]
I grabbed my fork of the game and played it with some people in my private event room. I will update a few cards that I don't think worked very well, but everyone enjoyed the cards.

**Comment by stevenvergenz** [comment]
Yeah, that's fine. We figured out our internal procedure for incorporating suggestions, so your new cards that pass QA will go live on Friday.

**Comment by stevenvergenz** [comment]
Thanks for your suggestions Grumpy! We've added ~20 of your cards to the live game. Would you be comfortable receiving credit for them? We're thinking about changing the "Holograms Against Humanity" text at the bottom of the cards to the creator's username for user-submitted cards.

**Comment by GrumpyCrouton** [comment]
Sure, I have no problem receiving credit for them.

**Pull request merged**
